### Практическое задание по теме "Системы линейных алгебраических уравнений"

#### 1. Решите линейную систему:

    | 1 2 3 |       | 12 |
    | 4 0 6 | * X = |  2 |
    | 7 8 9 |       |  1 |

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)
X

array([-9.2       ,  0.9       ,  6.46666667])

In [3]:
A.dot(X)

array([12.,  2.,  1.])

In [4]:
# через обратную матрицу
A1 = np.linalg.inv(A)  
print(A1)
print("det =", np.linalg.det(A1))
np.dot(A1, B)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
det = 0.016666666666666656


array([-9.2       ,  0.9       ,  6.46666667])

#### 2. Найдите псевдорешение:
    x + 2y – z = 1
    3x – 4y = 7
    8x – 5y + 2z = 12
    2x – 5z = 7
    11x + 4y – 7z = 15


In [5]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

<ipython-input-5-8bb72b0258ba>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [6]:
np.dot(A, [ 1.13919353, -0.90498444, -0.9009803 ])

array([ 0.23020495,  7.03751835, 11.83650984,  6.78328856, 15.21805317])

In [7]:
def Q(x, y, z):
    return((np.linalg.norm(np.dot(A, [x, y, z]) - B)) ** 2)
Q(1.13919353, -0.90498444, -0.9009803)

0.7152321111819737

#### 3. Сколько решений имеет линейная система:

    | 1 2 3 |       | 12 |
    | 4 5 6 | * X = |  2 |
    | 7 8 9 |       |  1 |
    
Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.det(A)
#np.linalg.solve(A, B)

0.0

#### 4. Вычислите LU-разложение матрицы:

    | 1  2  3 |
    | 2 16 21 |
    | 4 28 73 |

In [9]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


#### 5. Найдите нормальное псевдорешение недоопределенной системы:
    x + 2y – z = 1  
    8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум.

In [10]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])

np.linalg.lstsq(A, B)

<ipython-input-10-fcee22b1f6c8>:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

In [11]:
np.dot(A, [ 1.38191882, -0.18081181,  0.0202952 ])

array([ 1.        , 12.00000001])

In [12]:
def Q(x, y, z):
    return((np.linalg.norm(np.dot(A, [x, y, z]) - B)) ** 2)

Q(1.38191882, -0.18081181,  0.0202952)

1.0000001654807488e-16

In [13]:
def Q2(x, y, z):
    return(x ** 2 + y ** 2 + z ** 2)

Q2(1.38191882, -0.18081181,  0.0202952)

1.942804430848709

#### 6. Найдите одно из псевдорешений вырожденной системы:

    | 1 2 3 |       |  2 |
    | 4 5 6 | * X = |  5 |
    | 7 8 9 |       | 11 |

Попробуйте также отыскать и нормальное псевдорешение.

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [15]:
print(Q @ R)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [16]:
print(Q.T @ Q)

[[ 1.00000000e+00 -2.48218629e-16 -2.62094065e-17]
 [-2.48218629e-16  1.00000000e+00  2.82872043e-17]
 [-2.62094065e-17  2.82872043e-17  1.00000000e+00]]


In [17]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [18]:
B1 = (Q.T @ B) [:2]
B1

array([-1.21860576e+01,  3.55271368e-15])

In [19]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 3.92767275e-15])

In [20]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[1.50000000e+00 3.92767275e-15 0.00000000e+00]


1.499999999999996

In [21]:
np.linalg.norm(np.dot(A, X) - B)

1.224744871391589

In [22]:
X = np.array([1.5, 1, 0.5])
np.linalg.norm(X),  np.linalg.norm(np.dot(A, X) - B)

(1.8708286933869707, 15.297058540778355)